# Environment loosely based on https://github.com/conda/conda/blob/master/appveyor.yml

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\buildscripts\\appveyor\\run_with_env.cmd"

  matrix:
    # Since appveyor is quite slow, we only use a single configuration
    # and a subset of the test suite (see test_script below)
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "1.11"

init:
  # Use AppVeyor's provided Miniconda: https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_ARCH%" == "64" set MINICONDA=C:\Miniconda35-x64
  - if "%PYTHON_ARCH%" == "32" set MINICONDA=C:\Miniconda35
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

install:
  # Uncomment to download and install the latest Miniconda (XXX flaky)
  #- powershell .\\buildscripts\\appveyor\\install.ps1
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info
  - conda list
  - conda config --add channels numba
  - conda create -q -n testenv python=%PYTHON_VERSION% numpy=%NUMPY_VERSION% llvmlite cffi scipy
  - call activate testenv

build: false

test_script:
  # Build and test the package
  - python setup.py build_ext -q --inplace
  # Run a subset of the test suite, as AppVeyor is quite slow.
  # %CMD_IN_ENV% is needed for distutils/setuptools-based tests
  # on certain build configurations.
  - %CMD_IN_ENV% python runtests.py -b --tags important
