# This environment is used by the RTD config for PR builds. RTD uses this as the
# base environment and then adds in the sphinx etc tools on top.
# See: https://docs.readthedocs.io/en/stable/guides/conda.html
name: rtd
channels:
  - numba/label/dev
dependencies:
  - python=3.7
  - llvmlite
  - numpy
  - numpydoc
  - setuptools
  # The following is needed to fix RTD.
  - conda
