# This environment is used by the RTD config for PR builds. RTD uses this as the
# base environment and then adds in the sphinx etc tools on top.
# See: https://docs.readthedocs.io/en/stable/guides/conda.html
name: rtd
channels:
  - numba/label/dev
dependencies:
  - python=3.10
  - llvmlite=0.46
  - numpy
  - numpydoc
  - setuptools
  # https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-fileA
  - docutils==0.16
  # The following is needed to fix RTD.
  - conda
  - gxx_linux-64
