name: numba_win-64_builder

on:
  pull_request:
    paths:
      - .github/workflows/numba_win-64_builder.yml
      - buildscripts/condarecipe.local/**
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build (ignore cache)'
        type: boolean
        default: false
        required: false

jobs:
  win-64-build-conda:
    name: win-64-build-conda (py ${{ matrix.python-version }}, np ${{ matrix.numpy_build }})
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -elx {0}
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            numpy_build: "2.0"
          - python-version: "3.11"
            numpy_build: "2.0"
          - python-version: "3.12"
            numpy_build: "2.0"
          - python-version: "3.13"
            numpy_build: "2.1"
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache conda packages
        id: cache
        if: ${{ !inputs.force_build }}
        uses: actions/cache@v3
        with:
          path: |
            conda_channel_dir
          key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('buildscripts/condarecipe.local/**') }}
          restore-keys: |
            ${{ runner.os }}-conda-${{ matrix.python-version }}-

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""

      - name: Install conda-build
        run: conda install conda-build

      - name: Build Numba conda package
        if: steps.cache.outputs.cache-hit != 'true' || inputs.force_build
        run: |
          CONDA_CHANNEL_DIR="conda_channel_dir"
          mkdir -p $CONDA_CHANNEL_DIR
          conda build --debug -c numba/label/dev -c defaults \
            --python=${{ matrix.python-version }} \
            --numpy=${{ matrix.numpy_build }} \
            buildscripts/condarecipe.local/ \
            --output-folder=$CONDA_CHANNEL_DIR \
            --no-test

      - name: Upload numba conda package
        uses: actions/upload-artifact@v4
        with:
          name: numba_win-64_conda_py${{ matrix.python-version }}
          path: conda_channel_dir
          compression-level: 0
          retention-days: 7
          if-no-files-found: error

  win-64-test:
    name: win-64-test-conda (py ${{ matrix.python-version }}, np ${{ matrix.numpy_test }})
    needs: win-64-build-conda
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -elx {0}
    strategy:
      matrix:
        include:
          # Python 3.10
          - python-version: "3.10"
            numpy_test: "2.0"
          
          # Python 3.11
          - python-version: "3.11"
            numpy_test: "2.0"
          - python-version: "3.11"
            numpy_test: "2.1"
          
          # Python 3.12
          - python-version: "3.12"
            numpy_test: "2.0"
          - python-version: "3.12"
            numpy_test: "2.1"
          
          # Python 3.13
          - python-version: "3.13"
            numpy_test: "2.1"
      fail-fast: false

    steps:
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3

      - name: Download llvmlite artifact
        uses: actions/download-artifact@v4
        with:
          name: numba_win-64_conda_py${{ matrix.python-version }}

      - name: Install conda-build
        run: |
          conda install conda-build

      - name: Run tests
        env:
          TESTS_TO_RUN: "numba.tests"
          NUMBA_ENABLE_CUDASIM: 1
        run: |
          echo "Testing with NumPy ${{ matrix.numpy_test }}"
          conda build -c numba/label/dev -c defaults \
            --test \
            --numpy=${{ matrix.numpy_test }} \
            win-64/numba*.conda
